name: ilds_design_system
description: ICICI Lombard Design System (Flutter)
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Mulish/Mulish-Black.ttf
          weight: 900
